### ISSUE TITLE
boolean index did not match indexed array

### ISSUE THREAD

**Issue by rmh1480** [IBM/HOTT#2]
Hi,

After running main.py, I get the following error:

Traceback (most recent call last):
  File "./main.py", line 67, in <module>
    test_error = knn(X_train, X_test, y_train, y_test, methods[method], C, n_neighbors=7)
  File "HOTT/knn_classifier.py", line 25, in knn
    doc_to_train = [method(doc, x, C) for x in X_train.T]
  File "HOTT/knn_classifier.py", line 25, in <listcomp>
    doc_to_train = [method(doc, x, C) for x in X_train.T]
  File "HOTT/hott.py", line 11, in hott
    C_reduced = C[id_p][:, id_q]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 70 but corresponding boolean dimension is 552

Any pointers on how to resolve this issue are appreciated.
Best,
Raja

**Comment by EnnengYang** [comment]
You should change line 39 of main.py file to `bow_train, bow_test, y_train, y_test = train_test_split(bow_data, y)`

**Comment by rmh1480** [comment]
Same error after changing line 39 to:
bow_train, bow_test, y_train, y_test = train_test_split(bow_data, y)

Traceback (most recent call last):
  File "./main.py", line 67, in <module>
    test_error = knn(X_train, X_test, y_train, y_test, methods[method], C, n_neighbors=7)
  File "HOTT/knn_classifier.py", line 25, in knn
    doc_to_train = [method(doc, x, C) for x in X_train.T]
  File "HOTT/knn_classifier.py", line 25, in <listcomp>
    doc_to_train = [method(doc, x, C) for x in X_train.T]
  File "HOTT/hott.py", line 11, in hott
    C_reduced = C[id_p][:, id_q]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 70 but corresponding boolean dimension is 552

**Comment by EnnengYang** [comment]
You might also need to change the knn_classifier.py line 25
`doc_to_train = [method(doc, x, C) for x in X_train.T]`
 ->
`doc_to_train = [method(doc, x, C) for x in X_train]`

**Comment by YEN-GitHub** [comment]
Unfortunately, the `predict(neighbor_classes, C)` function in knn_classifier.py is still mistakes and may not work. I made a simple change that worked,
`def predict(neighbor_classes, C):
    # Make sure all classes are considered
    labels = np.concatenate((neighbor_classes, list(range(C))))
    # Find class frequency among neighbors
    labelclass = np.unique(labels, return_counts=True)
    weights = labelclass[1]
    # Find most popular class
    prediction = labelclass[0][np.argmax(weights)]

    # If most popular class is ambiguous try with fewer neighbors; else return
    # if sum(weights[prediction] == weights) > 1:
    #     return predict(neighbor_classes[:-2], C)
    # else:
    #     return prediction
    return prediction`

 but it was a bit different from what the author intended: 
`# If most popular class is ambiguous try with fewer neighbors;Else return) ` 
I didn't implement this.

Please let me know if you fix this problem.

**Comment by EnnengYang** [comment]
By the way, `hott(p, q, C, threshold=None)`  has a problem, so you can use the `def hoftt(p, q, C)` model first.

**Comment by moonfolk** [comment]
Hi all,

Thanks for pointing out the bugs. I've revised the code. All methods seem to run correctly now. Please let me know if you encounter any further issues.

Best,
Mikhail

**Comment by rmh1480** [comment]
Thanks Mikhail for fixing this issue, it is working now.

Best,
Raja
