### ISSUE TITLE
The results don't match the ones reported in paper

### ISSUE THREAD

**Issue by lxing532** [IBM/HOTT#3]
Hi,

I fixed the code by following the first issue post and ran the code on several datasets in paper. The results I got for HOFTT on most of the datasets are very poor. For example, the testing error for HOFTT on bbcsport is about 0.74.

Is there any bug hidden in the data.py? Especially for fit_topics.

**Comment by moonfolk** [comment]
Hi,

Thanks for bringing this up. I've gone over the code and corrected multiple bugs. Please let me know if you have any further issues reproducing the results.
